name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this based on your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'  # Update to a compatible Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Export the project
        run: npm run export

      - name: Deploy to GitHub Pages
        run: |
          if [ -d "./out" ]; then
            cp -r ./out/* ./some/deployment/directory/
          else
            echo "Error: Build output directory does not exist."
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
